# Autogenerated wrapper script for Carotid_jll for x86_64-linux-gnu
export libcarotid

JLLWrappers.@generate_wrapper_header("Carotid")
JLLWrappers.@declare_library_product(libcarotid, "libCarotid.so")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libcarotid,
        "lib/libCarotid.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
